"""
PDF export for the seven proof artifacts.

Uses reportlab (pure Python, no system dependencies) so it renders the same
locally and on Streamlit Community Cloud. reportlab's built-in Helvetica is
Latin-1; text is sanitized first so typographic characters (em dashes, smart
quotes) map to ASCII and anything else outside Latin-1 (e.g. an emoji in a
LinkedIn post) is dropped rather than breaking the render. Text is also
XML-escaped because reportlab Paragraphs use a mini-markup dialect.
"""

from io import BytesIO
from xml.sax.saxutils import escape

from reportlab.lib.colors import HexColor
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer

_REPLACEMENTS = {
    "—": "-", "–": "-", "‘": "'", "’": "'",
    "“": '"', "”": '"', "…": "...", "•": "-", " ": " ",
}


def _clean(text) -> str:
    """Sanitize any value to Latin-1-safe, XML-escaped text for reportlab."""
    if text is None:
        return ""
    text = str(text)
    for bad, good in _REPLACEMENTS.items():
        text = text.replace(bad, good)
    text = text.encode("latin-1", "ignore").decode("latin-1")
    return escape(text)


_TITLE = ParagraphStyle("title", fontName="Helvetica-Bold", fontSize=18, leading=22, spaceAfter=2)
_SUB = ParagraphStyle("sub", fontName="Helvetica", fontSize=12, leading=15, textColor=HexColor("#5a5a5a"), spaceAfter=10)
_H = ParagraphStyle("h", fontName="Helvetica-Bold", fontSize=13, leading=16, textColor=HexColor("#141414"), spaceBefore=10, spaceAfter=3)
_BODY = ParagraphStyle("body", fontName="Helvetica", fontSize=11, leading=16, textColor=HexColor("#282828"))
_HEADLINE = ParagraphStyle("headline", fontName="Helvetica-Bold", fontSize=11, leading=15, textColor=HexColor("#141414"))
_TAGS = ParagraphStyle("tags", fontName="Helvetica", fontSize=10, leading=14, textColor=HexColor("#5a5a5a"), spaceBefore=2)
_FOOT = ParagraphStyle("foot", fontName="Helvetica-Oblique", fontSize=9, leading=12, textColor=HexColor("#787878"), spaceBefore=12)


def build_pdf(facts: dict, artifacts: dict) -> bytes:
    """Render the facts + seven artifacts into a single PDF, returned as bytes."""
    buf = BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm, topMargin=16 * mm, bottomMargin=16 * mm,
        title="Proof Builder Output",
    )
    story = [
        Paragraph("Proof Builder Output", _TITLE),
        Paragraph(_clean(facts.get("title", "Untitled activity")), _SUB),
    ]

    def section(num, title, *paragraphs):
        story.append(Paragraph(f"{num}. {title}", _H))
        for p in paragraphs:
            story.append(p)

    section(1, "Resume bullet", Paragraph(_clean(artifacts.get("resume_bullet", "")), _BODY))
    section(2, "LinkedIn post", Paragraph(_clean(artifacts.get("linkedin_post", "")), _BODY))

    card = artifacts.get("portfolio_card", {}) or {}
    card_parts = [
        Paragraph(_clean(card.get("headline", "")), _HEADLINE),
        Paragraph(_clean(card.get("description", "")), _BODY),
    ]
    if card.get("tags"):
        card_parts.append(Paragraph("Tags: " + _clean(", ".join(card.get("tags", []))), _TAGS))
    section(3, "Portfolio card", *card_parts)

    section(4, "Proof summary", Paragraph(_clean(artifacts.get("proof_summary", "")), _BODY))

    skills = artifacts.get("skill_evidence", []) or []
    skill_parts = [
        Paragraph(f"- <b>{_clean(s.get('skill', ''))}</b>: {_clean(s.get('evidence', ''))}", _BODY)
        for s in skills
    ] or [Paragraph("", _BODY)]
    section(5, "Skill evidence breakdown", *skill_parts)

    section(6, "Recruiter-facing description", Paragraph(_clean(artifacts.get("recruiter_description", "")), _BODY))
    section(7, "Next-improvement suggestion", Paragraph(_clean(artifacts.get("improvement_suggestion", "")), _BODY))

    story.append(Spacer(1, 6))
    story.append(Paragraph(
        "Generated by Proof Builder Agent from a structured facts ledger "
        "(not from raw text), to keep every artifact honest to the same input.",
        _FOOT,
    ))

    doc.build(story)
    return buf.getvalue()
