"""
Proof Builder Agent — Streamlit UI.

Feed in one piece of completed student activity, get back seven ready-to-use
proof artifacts: resume bullet, LinkedIn post, portfolio card, proof summary,
skill evidence breakdown, recruiter-facing description, and a next-improvement
suggestion.

Run with:  streamlit run app.py
Requires a GROQ_API_KEY (see README.md / Groq_API_Guide_Caarya_Interns.docx).
"""

import json
import os

import streamlit as st
from dotenv import load_dotenv

from proof_builder import llm, pdf_export
from proof_builder.pipeline import run_pipeline

load_dotenv()

st.set_page_config(page_title="Proof Builder Agent", page_icon="🛠️", layout="wide")

# ---------------------------------------------------------------------------
# Sample activities, so reviewers (and the 3-activity submission requirement)
# have something ready to run without typing anything.
# ---------------------------------------------------------------------------
SAMPLES_PATH = os.path.join(os.path.dirname(__file__), "data", "sample_activities.json")


@st.cache_data
def load_samples():
    with open(SAMPLES_PATH, "r", encoding="utf-8") as f:
        return json.load(f)


def render_markdown_report(facts: dict, artifacts: dict) -> str:
    card = artifacts.get("portfolio_card", {})
    skills = artifacts.get("skill_evidence", [])
    skills_md = "\n".join(f"- **{s.get('skill', '')}** — {s.get('evidence', '')}" for s in skills)
    tags = ", ".join(card.get("tags", []))
    return f"""# Proof Builder Output — {facts.get('title', 'Untitled activity')}

## 1. Resume bullet
{artifacts.get('resume_bullet', '')}

## 2. LinkedIn post
{artifacts.get('linkedin_post', '')}

## 3. Portfolio card
**{card.get('headline', '')}**
{card.get('description', '')}
Tags: {tags}

## 4. Proof summary
{artifacts.get('proof_summary', '')}

## 5. Skill evidence breakdown
{skills_md}

## 6. Recruiter-facing description
{artifacts.get('recruiter_description', '')}

## 7. Next-improvement suggestion
{artifacts.get('improvement_suggestion', '')}

---
*Generated by Proof Builder Agent from the facts ledger below (not from raw free text), to keep every artifact honest to the same input.*

```json
{json.dumps({k: v for k, v in facts.items() if k not in ("raw_input", "is_thin")}, indent=2)}
```
"""


# ---------------------------------------------------------------------------
# Sidebar
# ---------------------------------------------------------------------------
with st.sidebar:
    st.markdown("### 🛠️ Proof Builder Agent")
    st.caption("One piece of work in. Seven ready-to-use proof artifacts out.")
    st.divider()
    st.markdown("**Setup**")
    key_present = bool(os.environ.get("GROQ_API_KEY"))
    if key_present:
        st.success("GROQ_API_KEY detected.")
    else:
        st.warning("GROQ_API_KEY not set.")
        st.caption(
            "Get a free key at [console.groq.com](https://console.groq.com), then add it to a "
            "`.env` file as `GROQ_API_KEY=...` and restart the app. See "
            "`Groq_API_Guide_Caarya_Interns.docx` for the full walkthrough."
        )
    st.caption(f"Model: `{llm.DEFAULT_MODEL}`")
    st.divider()
    st.markdown("**How it stays honest**")
    st.caption(
        "Every input first gets reduced to a structured facts ledger. All seven outputs are "
        "generated only from that ledger — never from the raw text directly — so nothing can "
        "drift, contradict, or quietly get more impressive between artifacts."
    )

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
st.title("Proof Builder Agent")
st.write(
    "Describe one piece of work you actually completed. You'll get back a resume bullet, a "
    "LinkedIn post, a portfolio card, a proof summary, a skill evidence breakdown, a "
    "recruiter-facing description, and a next-improvement suggestion — each meant to be usable as-is."
)

samples = load_samples()
sample_titles = ["— write my own —"] + [s["title"] for s in samples]
choice = st.selectbox("Start from a sample activity, or write your own", sample_titles)

default_text = ""
if choice != sample_titles[0]:
    default_text = next(s["activity_text"] for s in samples if s["title"] == choice)

activity_text = st.text_area(
    "What did you do?",
    value=default_text,
    height=160,
    placeholder=(
        "E.g. Built a Chrome extension that highlights inaccessible color contrast on any "
        "webpage. Used JavaScript and the Chrome extensions API, tested it on 10 real sites, "
        "shared it in the campus dev club Discord and three people used it on their own projects."
    ),
)

generate_clicked = st.button("Generate proof", type="primary", disabled=not activity_text.strip())

if generate_clicked:
    with st.spinner("Extracting facts, then generating all seven artifacts..."):
        try:
            result = run_pipeline(activity_text)
            st.session_state["result"] = result
        except llm.ProofBuilderLLMError as exc:
            st.session_state.pop("result", None)
            st.error(str(exc))
        except ValueError as exc:
            st.session_state.pop("result", None)
            st.error(str(exc))

result = st.session_state.get("result")

if result:
    facts = result["facts"]
    artifacts = result["artifacts"]

    if facts.get("is_thin"):
        st.info(
            "This activity description was fairly thin, so outputs were generated conservatively "
            "rather than padded out. Add more detail above and regenerate for richer artifacts."
        )

    with st.expander("Facts ledger extracted from your input (what every output is grounded in)"):
        st.json({k: v for k, v in facts.items() if k not in ("raw_input",)})

    tabs = st.tabs(
        [
            "Resume bullet",
            "LinkedIn post",
            "Portfolio card",
            "Proof summary",
            "Skill evidence",
            "Recruiter description",
            "Improvement suggestion",
        ]
    )

    with tabs[0]:
        st.text_area("Resume bullet", artifacts["resume_bullet"], height=100, label_visibility="collapsed")

    with tabs[1]:
        st.text_area("LinkedIn post", artifacts["linkedin_post"], height=180, label_visibility="collapsed")

    with tabs[2]:
        card = artifacts["portfolio_card"]
        st.subheader(card.get("headline", ""))
        st.write(card.get("description", ""))
        if card.get("tags"):
            st.write(" ".join(f"`{t}`" for t in card["tags"]))

    with tabs[3]:
        st.write(artifacts["proof_summary"])

    with tabs[4]:
        for item in artifacts["skill_evidence"]:
            st.markdown(f"**{item.get('skill', '')}** — {item.get('evidence', '')}")

    with tabs[5]:
        st.write(artifacts["recruiter_description"])

    with tabs[6]:
        st.write(artifacts["improvement_suggestion"])

    st.divider()
    report_md = render_markdown_report(facts, artifacts)
    dl_md, dl_pdf = st.columns(2)
    with dl_md:
        st.download_button(
            "Download full report (Markdown)",
            data=report_md,
            file_name="proof_builder_output.md",
            mime="text/markdown",
            use_container_width=True,
        )
    with dl_pdf:
        st.download_button(
            "Download full report (PDF)",
            data=pdf_export.build_pdf(facts, artifacts),
            file_name="proof_builder_output.pdf",
            mime="application/pdf",
            use_container_width=True,
        )
